// The libraries are loaded via script tags in index.html, so we access them globally.
const { jsPDF } = window.jspdf;

// --- Utility Functions (Date Range & File Naming) ---

/**
 * Gets the start and end dates for the previous month, and the report name.
 * @param {string} type 'transactions' or 'service-repairs'
 * @returns {{startDate: string, endDate: string, fileName: string, reportPeriod: string, monthYearTitle: string}}
 */
function getLastMonthDetails(type) {
    const now = new Date();
    const firstDayCurrentMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    const endDate = new Date(firstDayCurrentMonth);
    endDate.setDate(endDate.getDate() - 1);
    const startDate = new Date(endDate.getFullYear(), endDate.getMonth(), 1);

    const formatDate = (date) => {
        const year = date.getFullYear();
        const month = String(date.getMonth() + 1).padStart(2, '0');
        const day = String(date.getDate()).padStart(2, '0');
        return `${year}-${month}-${day}`;
    };

    const fileMonth = String(endDate.getMonth() + 1).padStart(2, '0');
    const fileYear = endDate.getFullYear();

    // Determine prefix based on report type
    let prefix = 'T';
    let titlePrefix = 'Transaction';
    if (type === 'service-repairs') {
        prefix = 'S';
        titlePrefix = 'Service/Repair';
    }

    const fileName = `${prefix}${fileYear}${fileMonth}.pdf`;
    const monthName = endDate.toLocaleString('default', { month: 'long' });

    return {
        startDate: formatDate(startDate),
        endDate: formatDate(endDate),
        fileName: fileName,
        reportPeriod: `${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`,
        monthYearTitle: `${titlePrefix} Report for ${monthName} ${fileYear}`
    };
}


// --- Helper Function for PDF Header/Footer ---

function addHeaderFooter(doc, pageNum, companyDetails) {
    const pageHeight = doc.internal.pageSize.height;
    const margin = 15;
    const headerY = 10;
    const footerY = pageHeight - 10;

    // --- Header ---
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);

    // Company Name (Right-aligned, Top)
    doc.setFont('helvetica', 'bold');
    doc.text(companyDetails.name, doc.internal.pageSize.width - margin, headerY, { align: 'right' });

    // Company Contact/Address (Right-aligned, Below Name)
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(companyDetails.address + " | " + companyDetails.contact, doc.internal.pageSize.width - margin, headerY + 4, { align: 'right' });

    doc.setDrawColor(200, 200, 200);
    doc.line(margin, headerY + 7, doc.internal.pageSize.width - margin, headerY + 7);

    // --- Footer ---
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);

    // System Generated Time (Left-aligned, bottom)
    doc.text(`System generated on: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, margin, footerY);

    // Page Number (Right-aligned, bottom)
    doc.text(`Page ${pageNum}`, doc.internal.pageSize.width - margin, footerY, { align: 'right' });
}


// --- PDF Generation Logic: Transactions (Existing logic) ---

function generateTransactionReport(data, reportPeriod, fileName) {
    const doc = new jsPDF('p', 'mm', 'a4');
    const margin = 15;
    const companyDetails = {
        name: "JEFFIX Auto Repair",
        address: "ST. Anne Deca Homes, Marilao, Philippines, 3019",
        contact: "jeffixofficial@gmail.com | (+63) 927 987 5521"
    };

    const totalTransactions = data.length;
    const totalIncome = data.reduce((sum, row) => sum + parseFloat(row.total_amount), 0);
    let yOffset = 25;

    addHeaderFooter(doc, 1, companyDetails);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(33, 33, 33);
    doc.text('Transaction Report', margin, yOffset);
    yOffset += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    doc.text(`Period: ${reportPeriod}`, margin, yOffset);
    yOffset += 5;

    doc.text(`Report Generated By: System Generated`, margin, yOffset);
    yOffset += 10;

    // DISPLAY SUMMARY
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');

    doc.text(`Number of Transactions: ${totalTransactions}`, margin, yOffset);
    doc.text(`Total Income: ₱${totalIncome.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 70, yOffset);
    yOffset += 8;

    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yOffset - 3, doc.internal.pageSize.width - margin, yOffset - 3);

    // Table Data and Configuration
    const tableHeaders = [
        'Transaction ID',
        'Customer Name',
        'Vehicle (Plate)',
        'Total Cost',
        'Payment Date'
    ];

    const tableData = data.map(row => [
        row.invoice_number,
        row.customer_name,
        `${row.vehicle_brand} (${row.vehicle_plate})`,
        `₱${parseFloat(row.total_amount).toFixed(2)}`,
        new Date(row.payment_date).toLocaleDateString()
    ]);

    doc.autoTable({
        startY: yOffset,
        head: [tableHeaders],
        body: tableData,
        theme: 'striped',
        styles: { fontSize: 9, cellPadding: 3, valign: 'middle' },
        headStyles: { fillColor: [72, 30, 20], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [247, 247, 247] },
        didParseCell: function (data) {
            if (data.column.index === 3) {
                data.cell.styles.halign = 'right';
            }
        },
        didDrawPage: (data) => {
            addHeaderFooter(doc, data.pageNumber, companyDetails);
        }
    });

    const pdfData = doc.output('datauristring');

    fetch('../../b/gr/createT.php', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ fileName: fileName, pdfData: pdfData.split(',')[1] })
    })
        .then(response => response.json())
        .then(result => {
            if (result.success) {
                displayReportList('transactions');
            } else {
                console.error(`Failed to save PDF on server: ${result.message}`);
            }
        })
        .catch(error => { console.error("Error sending PDF data to server:", error); });
}


// --- NEW PDF Generation Logic: Service/Repair (UPDATED FOR NEW SCHEMA) ---

/**
 * Generates the Service/Repair Report PDF.
 * @param {Array<Object>} data Detailed service data.
 * @param {Array<Object>} summary Service usage count summary.
 */
function generateServiceReport(data, summary, reportPeriod, fileName) {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageHeight = doc.internal.pageSize.height;
    const margin = 15;
    const companyDetails = {
        name: "JEFFIX Auto Repair",
        address: "ST. Anne Deca Homes, Marilao, Philippines, 3019",
        contact: "jeffixofficial@gmail.com | (+63) 927 987 5521"
    };

    let yOffset = 25;

    addHeaderFooter(doc, 1, companyDetails);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(33, 33, 33);
    doc.text('Service/Repair Report', margin, yOffset);
    yOffset += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    doc.text(`Period: ${reportPeriod}`, margin, yOffset);
    yOffset += 5;

    doc.text(`Report Generated By: System Generated`, margin, yOffset);
    yOffset += 10;

    // --- DISPLAY SERVICE USAGE SUMMARY ---
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Service Usage Summary:', margin, yOffset);
    yOffset += 5;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    const summaryX = margin + 5;
    const summaryYStart = yOffset;
    let currentSummaryY = summaryYStart;

    summary.forEach(item => {
        // Handle page break for summary list if needed
        if (currentSummaryY + 4 > pageHeight - margin) {
            doc.addPage();
            addHeaderFooter(doc, doc.internal.pages.length, companyDetails);
            currentSummaryY = 25; // Reset Y for new page
        }
        doc.text(`- ${item.service_name}: ${item.count} uses`, summaryX, currentSummaryY);
        currentSummaryY += 5;
    });

    yOffset = currentSummaryY + 5; // Resume offset after summary block

    doc.setDrawColor(200, 200, 200);
    doc.line(margin, yOffset - 3, doc.internal.pageSize.width - margin, yOffset - 3);


    // --- Table Data and Configuration ---
    const tableHeaders = [
        'Job Order #',
        'Service Type',
        'Assigned Mechanic(s)', // Updated Label
        'Duration (Days)',
        'Status'
    ];

    const tableData = data.map(row => {
        let durationDays = 'N/A';
        // Calculate duration in days using 'started_at' and 'completed_at' from job_service
        if (row.completed_at && row.started_at) {
            const startDate = new Date(row.started_at);
            const endDate = new Date(row.completed_at);
            const durationMs = endDate.getTime() - startDate.getTime();
            // Calculate in days, minimum 1 day if completed on the same or next day
            durationDays = Math.max(1, Math.ceil(durationMs / (1000 * 60 * 60 * 24)));
            durationDays = `${durationDays} day(s)`;
        }

        return [
            row.job_order_number, // Mapped to jobs.display_id
            row.service_name,
            row.assigned_mechanic, // Mapped via GROUP_CONCAT
            durationDays,
            row.status // Job status
        ];
    });

    doc.autoTable({
        startY: yOffset,
        head: [tableHeaders],
        body: tableData,
        theme: 'striped',
        styles: { fontSize: 9, cellPadding: 3, valign: 'middle' },
        headStyles: { fillColor: [72, 30, 20], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [247, 247, 247] },
        didDrawPage: (data) => {
            addHeaderFooter(doc, data.pageNumber, companyDetails);
        }
    });

    const pdfData = doc.output('datauristring');

    // Send the PDF data to PHP to be saved
    fetch('../../b/gr/createSR.php', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ fileName: fileName, pdfData: pdfData.split(',')[1] })
    })
        .then(response => response.json())
        .then(result => {
            if (result.success) {
                displayReportList('service-repairs');
            } else {
                console.error(`Failed to save PDF on server: ${result.message}`);
            }
        })
        .catch(error => { console.error("Error sending PDF data to server:", error); });
}


// --- Report Listing Logic (Existing logic) ---

async function displayReportList(reportType) {
    const listContainer = document.getElementById('report-list');
    const summaryContainer = document.getElementById('report-summary');
    listContainer.innerHTML = '';
    summaryContainer.innerHTML = '';

    if (reportType !== 'transactions' && reportType !== 'service-repairs') {
        summaryContainer.innerHTML = `<p style="color: #FF4E1F;">Report listing is only available for Transaction and Service/Repair reports.</p>`;
        return;
    }

    try {
        const response = await fetch('../../b/gr/fetchReports.php');
        if (!response.ok) throw new Error('Failed to fetch report list.');

        const result = await response.json();

        if (result.success && result.reports.length > 0) {

            const prefix = (reportType === 'transactions') ? 'T' : 'S';

            const filteredReports = result.reports.filter(report => report.filename.startsWith(prefix));

            if (filteredReports.length === 0) {
                summaryContainer.innerHTML = `<p>No ${reportType.replace('-', '/')} Reports found in the 'b/gr' folder.</p>`;
                return;
            }

            summaryContainer.innerHTML = `
                <p>Found <span>${filteredReports.length}</span> existing ${reportType.replace('-', '/')} Reports.</p>
            `;

            filteredReports.forEach(report => {
                const item = document.createElement('div');
                item.className = 'report-item';
                item.innerHTML = `
                    <div class="report-details">
                        <div class="report-title">${report.title}</div>
                        <div class="report-meta">Generated: ${new Date(report.generated_on).toLocaleString()}</div>
                    </div>
                    <div class="report-actions">
                        <a href="../../b/gr/reports/${report.filename}" target="_blank">
                            <button>View</button>
                        </a>
                        <a href="../../b/gr/reports/${report.filename}" download="${report.filename}">
                            <button><i class="fas fa-download"></i> Download</button>
                        </a>
                    </div>
                `;
                listContainer.appendChild(item);
            });
        } else {
            summaryContainer.innerHTML = `<p>No Reports found in the 'b/gr' folder.</p>`;
        }
    } catch (error) {
        console.error("Error listing reports:", error);
        summaryContainer.innerHTML = `<p style="color: red;">Error loading report list: ${error.message}</p>`;
    }
}


// --- Initial Load & Filter Logic ---

document.addEventListener('DOMContentLoaded', () => {
    if (!window.jspdf || !window.jspdf.jsPDF) {
        console.error("jspdf library is missing. Please ensure jspdf.umd.min.js and jspdf.plugin.autotable.min.js are linked in index.html.");
        return;
    }

    const filterDropdown = document.getElementById('gr-filter-type');

    // --- Filter Change Listener ---
    filterDropdown.addEventListener('change', (event) => {
        const selectedType = event.target.value;
        if (selectedType === 'transactions' || selectedType === 'service-repairs') {
            displayReportList(selectedType);
            checkAndGenerateReport(selectedType);
        } else {
            document.getElementById('report-summary').innerHTML = '';
            document.getElementById('report-list').innerHTML = '';
        }
    });

    // --- Function to handle checking and generating both report types ---
    function checkAndGenerateReport(reportType) {
        const { startDate, endDate, fileName, reportPeriod, monthYearTitle } = getLastMonthDetails(reportType);

        console.log(`Checking for last month's ${reportType} report: ${fileName}`);

        const fetchScript = (reportType === 'transactions') ? 'fetchT.php' : 'fetchSR.php';

        fetch(`../../b/gr/${fetchScript}`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                report_type: reportType,
                start_date: startDate,
                end_date: endDate,
                file_name: fileName
            })
        })
            .then(response => {
                if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
                return response.json();
            })
            .then(data => {
                if (data.success && data.should_create) {
                    console.log(`${monthYearTitle} not found. Generating PDF...`);
                    if (data.data && data.data.length > 0) {
                        console.log(data);
                        if (reportType === 'transactions') {
                            generateTransactionReport(data.data, reportPeriod, fileName);
                        } else if (reportType === 'service-repairs') {
                            generateServiceReport(data.data, data.summary, reportPeriod, fileName);
                        }
                    } else {
                        console.log(data);
                        console.log(`No data found for ${reportType} last month. PDF creation skipped.`);
                        displayReportList(reportType);
                    }
                } else if (data.success && !data.should_create) {
                    console.log(`${monthYearTitle} already exists. No action taken.`);
                    displayReportList(reportType);
                } else {
                    console.error("Server error:", data.message);
                }
            })
            .catch(error => {
                console.error(`Error during initial ${reportType} report check:`, error);
            });
    }

    // You may add a default call here if you want a report to load on page open
    // For example: checkAndGenerateReport('transactions');
});